/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package core.gui;

import java.awt.Toolkit;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.Inet4Address;
import java.net.Inet6Address;
import java.net.UnknownHostException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.LookAndFeel;
import javax.swing.SwingWorker;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Jayawickrama
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        btnIPV6.setEnabled(false);
        seticon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        btnIPV6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btnIPV4 = new javax.swing.JButton();
        txt_file_path = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Network Monitor");

        jTextPane1.setText("www.facebook.com\nwww.yahoo.com\nwww.live.com\nwww.wikipedia.org\nwww.msn.com\nwww.microsoft.com\nwww.blogspot.com\nwww.baidu.com\nwww.qq.com\nwww.mozilla.com\nwww.sina.com.cn\nwww.wordpress.com\nwww.bing.com\nwww.adobe.com\nwww.163.com\nwww.taobao.com\nwww.soso.com\nwww.twitter.com\nwww.youku.com\nwww.ask.com\nwww.sohu.com\nwww.amazon.com\nwww.windows.com\nwww.ebay.com\nwww.yahoo.co.jp\nwww.myspace.com\nwww.apple.com\nwww.tudou.com\nwww.conduit.com\nwww.hotmail.com\nwww.flickr.com\nwww.photobucket.com\nwww.tianya.cn\nwww.about.com\nwww.cnet.com\nwww.hao123.com\nwww.iefxz.com\nwww.xunlei.com\nwww.paypal.com\nwww.rapidshare.com\nwww.go.com\nwww.fc2.com\nwww.bbc.co.uk\nwww.imdb.com\nwww.orkut.com\nwww.sogou.com\nwww.56.com\nwww.aol.com\nwww.craigslist.org\nwww.rakuten.co.jp\nwww.imageshack.us\nwww.ku6.com\nwww.blogger.com\nwww.goo.ne.jp\nwww.ifeng.com\nwww.linkedin.com\nwww.yandex.ru\nwww.mail.ru\nwww.partypoker.com\nwww.megaupload.com\nwww.answers.com\nwww.alibaba.com\nwww.hi5.com\nwww.cnn.com\nwww.amazon.co.jp\nwww.4shared.com\nwww.ameblo.jp\nwww.gougou.com\nwww.skype.com\nwww.renren.com\nwww.dailymotion.com\nwww.naver.com\nwww.weather.com\nwww.mozilla.org\nwww.mediafire.com\nwww.bit.ly\nwww.hp.com\nwww.livedoor.jp\nwww.ehow.com\nwww.nifty.com\nwww.vkontakte.ru\nwww.alipay.com\nwww.nytimes.com\nwww.overture.com\nwww.sourceforge.net\nwww.fbcdn.net\nwww.xtendmedia.com\nwww.xinhuanet.com\nwww.wikimedia.org\nwww.pconline.com.cn\nwww.daum.net\nwww.4399.com\nwww.bankofamerica.com\nwww.ebay.de\nwww.uol.com.br\nwww.filestube.com\nwww.zol.com.cn\nwww.mop.com\nwww.alexa.com\nwww.biglobe.ne.jp");
        jScrollPane1.setViewportView(jTextPane1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setText("URL List");

        btnIPV6.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnIPV6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/core/image/network-icon.png"))); // NOI18N
        btnIPV6.setText("Start Analyze  IPV6");
        btnIPV6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIPV6ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "URL", "IPV4 address", "IPV4 Response  Time", "IPV6 address", "IPV6 Response  Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setMinWidth(70);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(70);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/core/image/Generate-tables-icon.png"))); // NOI18N
        jButton2.setText("Export Result to CSV");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnIPV4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnIPV4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/core/image/network-icon.png"))); // NOI18N
        btnIPV4.setText("Start Analyze  IPV4");
        btnIPV4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIPV4ActionPerformed(evt);
            }
        });

        txt_file_path.setEditable(false);

        jLabel2.setText("File Path :");

        jButton4.setText("Browse");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem2.setText("Clear URL List");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIPV4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIPV6, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_file_path, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIPV4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIPV6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_file_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIPV6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIPV6ActionPerformed
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                // Simulate doing something useful.
                getIPV6Set();
                return null;
            }
        };
        
        worker.execute();
    }//GEN-LAST:event_btnIPV6ActionPerformed
    
    private void btnIPV4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIPV4ActionPerformed
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                // Simulate doing something useful.
                getIPV4Set();
                return null;
            }
        };
        
        worker.execute();
        
    }//GEN-LAST:event_btnIPV4ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txt_file_path.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Select file path first", "Empty file path", JOptionPane.ERROR_MESSAGE);
        } else {
            toExcel(jTable1, txt_file_path.getText());
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            txt_file_path.setText(chooser.getSelectedFile().getAbsolutePath() + System.getProperty("file.separator") + "result@" + new SimpleDateFormat("yyyy_MM_dd_hh_mm_ss").format(new Date()) + ".csv");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jTextPane1.setText("");
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                          UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception e) {
                }
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIPV4;
    private javax.swing.JButton btnIPV6;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextField txt_file_path;
    // End of variables declaration//GEN-END:variables

    public void toExcel(JTable table, String file_path) {
        try {
            File file = new File(file_path);
            TableModel model = table.getModel();
            FileWriter excel = new FileWriter(file);
            
            for (int i = 0; i < model.getColumnCount(); i++) {
                excel.write(model.getColumnName(i) + ",");
            }
            
            excel.write("\n");
            
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    excel.write(model.getValueAt(i, j).toString() + ",");
                }
                excel.write("\n");
            }
            
            excel.close();
            
        } catch (IOException e) {
            System.out.println(e);
        }
    }
    
    private long getPingTime(String ip) {
        long time = 0;
        try {
            long start = System.nanoTime();
            String command = "ping  " + ip;
            Process process = Runtime.getRuntime().exec(command);
            process.getOutputStream();
            long finish = System.nanoTime();
            time = finish - start;
        } catch (Exception e) {
        }
        return time;
    }
    
    public void getIPV4Set() {
        
        if (jTable1.getRowCount() < 1) {
            String[] domain = jTextPane1.getText().split("\n");
            
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            for (int i = 0; i < domain.length; i++) {
                String domian_name = domain[i];
                Vector v = new Vector();
                v.add(i);
                v.add(domian_name);
                Inet4Address ip_address = null;
                try {
                    //Inet4Address a = (Inet6Address) Inet6Address.getByName("www.google.com");
                    ip_address = (Inet4Address) Inet4Address.getByName(domian_name);
                    v.add(ip_address.getHostAddress());
                    v.add(getPingTime(ip_address.getHostAddress()));
                } catch (UnknownHostException ex) {
                    JOptionPane.showMessageDialog(null, "Errr occurd" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    continue;
                }
                
                v.add("");
                v.add("");
                dtm.addRow(v);
            }
            
        }
        
        btnIPV6.setEnabled(true);
    }
    
    private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
    private void getIPV6Set() {
        if (jTable1.getRowCount() < 1) {
            String[] domain = jTextPane1.getText().split("\n");
            
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            for (int i = 0; i < domain.length; i++) {
                String host_name = dtm.getValueAt(i, 1).toString();
                Inet6Address ip_address = null;
                try {
                    ip_address = (Inet6Address) Inet6Address.getByName(host_name);
                    dtm.setValueAt(ip_address.getHostAddress(), i, 4);
                    dtm.setValueAt(getPingTime(ip_address.getHostAddress()), i, 5);
                } catch (UnknownHostException ex) {
                    JOptionPane.showMessageDialog(null, "Errr occurd" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    continue;
                }
                
            }
        }
    }
}
