/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package core.gui;

import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.ListModel;
import javax.swing.SwingWorker;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import util.DNSStuff;
import util.Ping;

public class MainFrame extends javax.swing.JFrame
{
    /**
     * Creates new form MainFrame
     */
    public MainFrame()
    {
	initComponents();
	btnStartIPv6Test.setEnabled( false );
	setApplicationIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblUrlList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTests = new javax.swing.JTable();
        btnStartIPv4Test = new javax.swing.JButton();
        btnStartIPv6Test = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstUrls = new javax.swing.JList<>( new DefaultListModel() );
        btnAddUrls = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Network Monitor");

        lblUrlList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUrlList.setForeground(new java.awt.Color(51, 51, 0));
        lblUrlList.setText("URL List");

        tblTests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "URL", "IPv4 Address", "IPv4 Ping", "IPv4 MX Address", "IPv6 Address", "IPv6 Ping", "IPv6 MX Address"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblTests.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblTests);
        if (tblTests.getColumnModel().getColumnCount() > 0)
        {
            tblTests.getColumnModel().getColumn(0).setMinWidth(70);
            tblTests.getColumnModel().getColumn(0).setPreferredWidth(70);
            tblTests.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        btnStartIPv4Test.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnStartIPv4Test.setIcon(new javax.swing.ImageIcon(getClass().getResource("/core/image/network-icon.png"))); // NOI18N
        btnStartIPv4Test.setText("Start IPv4 Test");
        btnStartIPv4Test.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnStartIPv4TestActionPerformed(evt);
            }
        });

        btnStartIPv6Test.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnStartIPv6Test.setIcon(new javax.swing.ImageIcon(getClass().getResource("/core/image/network-icon.png"))); // NOI18N
        btnStartIPv6Test.setText("Start IPv6 Test");
        btnStartIPv6Test.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnStartIPv6TestActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lstUrls);

        btnAddUrls.setText("Add URLs");
        btnAddUrls.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddUrlsActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAddUrls)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStartIPv4Test, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStartIPv6Test, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
                    .addComponent(lblUrlList, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUrlList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnStartIPv4Test, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStartIPv6Test, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addComponent(btnAddUrls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartIPv6TestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartIPv6TestActionPerformed
	new SwingWorker<Void, Void>()
	{
	    @Override
	    protected Void doInBackground() throws Exception
	    {
		// Simulate doing something useful.
		performIPv6Tests();
		return null;
	    }
	}.execute();
    }//GEN-LAST:event_btnStartIPv6TestActionPerformed

    private void btnStartIPv4TestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartIPv4TestActionPerformed
	new SwingWorker<Void, Void>()
	{
	    @Override
	    protected Void doInBackground() throws Exception
	    {
		// Simulate doing something useful.
		performIPv4Tests();
		return null;
	    }
	}.execute();
    }//GEN-LAST:event_btnStartIPv4TestActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
	System.exit( 0 );
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnAddUrlsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddUrlsActionPerformed
    {//GEN-HEADEREND:event_btnAddUrlsActionPerformed
	final JFileChooser fileChooser = new JFileChooser();

	int rVal = fileChooser.showOpenDialog( this );
	if( rVal == JFileChooser.APPROVE_OPTION )
	{
	    addUrlsFromFile( fileChooser.getSelectedFile() );
	}
    }//GEN-LAST:event_btnAddUrlsActionPerformed

    public static void main( final String args[] )
    {
	/* Create and display the form */
	java.awt.EventQueue.invokeLater( new Runnable()
	{
	    public void run()
	    {
		try
		{
		    UIManager.setLookAndFeel( UIManager.getSystemLookAndFeelClassName() );
		}
		catch( final ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e )
		{
		}

		new MainFrame().setVisible( true );
	    }
	} );
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUrls;
    private javax.swing.JButton btnStartIPv4Test;
    private javax.swing.JButton btnStartIPv6Test;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUrlList;
    private javax.swing.JList<String> lstUrls;
    private javax.swing.JTable tblTests;
    // End of variables declaration//GEN-END:variables

    private final List<String> mUrls = new ArrayList<>();

    private void setApplicationIcon()
    {
	setIconImage( Toolkit.getDefaultToolkit().getImage( getClass().getResource( "icon.png" ) ) );
    }

    public void performIPv4Tests()
    {
	if( tblTests.getRowCount() < 1 )
	{
	    final DefaultTableModel dtm = (DefaultTableModel) tblTests.getModel();
	    for( final String url : mUrls )
	    {
		final String address = DNSStuff.getIPv4Address( url );
		final Object[] row = new Object[]
		{
		    url,
		    address,
		    Ping.IPv4( address )
		};

		dtm.addRow( row );
	    }
	}

	btnStartIPv6Test.setEnabled( true );
    }

    private void performIPv6Tests()
    {
	if( tblTests.getRowCount() < 1 )
	{
	    final DefaultTableModel dtm = (DefaultTableModel) tblTests.getModel();
	    for( int i = 0; i < mUrls.size(); i++ )
	    {
		final String url = mUrls.get( i );

		final String address = DNSStuff.getIPv6Address( url );
		dtm.setValueAt( address, i, 4 );
		dtm.setValueAt( Ping.IPv6( address ), i, 5 );
	    }
	}
    }

    private void addUrlsFromFile( final File file )
    {
	try
	{
	    final BufferedReader reader = new BufferedReader( new FileReader( file ) );
	    final DefaultListModel listModel = (DefaultListModel) lstUrls.getModel();

	    String line;
	    while( ( line = reader.readLine() ) != null )
	    {
		line = line.replace( "http:", "" ).replaceAll( "/", "" );
		mUrls.add( line );

		listModel.addElement( line );
	    }
	}
	catch( final IOException ex )
	{
	    Logger.getLogger( MainFrame.class.getName() ).log( Level.SEVERE, null, ex );
	}
    }
}
